"""Extractor de ChEBI (sección 3 de docs/MANUAL.md): compuestos, nombres y ontología.

Descarga los archivos TSV de `flat_files/` del FTP oficial de EMBL-EBI, que solo
contienen IDs primarios, junto con su README, que declara el número de release.

TODO: `structures.tsv.gz` (SMILES e InChI, ~89 MB) y `reference.tsv.gz` (~131 MB)
todavía no se descargan; se agregan cuando una etapa los use.
"""

from __future__ import annotations

from pathlib import Path

from metabo.download import Downloader
from metabo.errors import SourceFormatError
from metabo.manifest import DownloadRecord
from metabo.sources.formats import check_header, find_release

FUENTE = "chebi"
BASE_URL = "https://ftp.ebi.ac.uk/pub/databases/chebi/flat_files"
README_URL = f"{BASE_URL}/README"

_RELEASE = r"^\*\s*ChEBI Release:\s*([0-9]+)\s*$"

# Archivo -> encabezado esperado (copiado de los archivos del release 256).
TSV_FILES: dict[str, tuple[str, ...]] = {
    "compounds.tsv.gz": (
        "id",
        "name",
        "status_id",
        "source",
        "parent_id",
        "merge_type",
        "chebi_accession",
        "definition",
        "ascii_name",
        "stars",
        "modified_on",
        "release_date",
    ),
    "chemical_data.tsv.gz": (
        "id",
        "compound_id",
        "formula",
        "charge",
        "mass",
        "monoisotopic_mass",
        "status_id",
        "structure_id",
        "is_autogenerated",
    ),
    "names.tsv.gz": (
        "id",
        "compound_id",
        "name",
        "type",
        "status_id",
        "adapted",
        "language_code",
        "ascii_name",
    ),
    "relation.tsv.gz": (
        "id",
        "relation_type_id",
        "init_id",
        "final_id",
        "status_id",
        "evidence_accession",
        "evidence_source_id",
    ),
    "relation_type.tsv.gz": ("id", "code", "allow_cycles", "description"),
    "secondary_ids.tsv.gz": ("compound_id", "secondary_id"),
}


def parse_release(text: str) -> str:
    """Número de release declarado en el README de flat_files/."""
    return find_release(text, _RELEASE, "el README de ChEBI flat_files")


def extract(downloader: Downloader, raw_dir: Path) -> tuple[str, list[DownloadRecord]]:
    """Descarga la versión vigente de ChEBI a raw/chebi/<release>/."""
    release = parse_release(downloader.fetch_text(FUENTE, README_URL))

    records = [downloader.download(FUENTE, README_URL, release)]
    for filename, expected in TSV_FILES.items():
        record = downloader.download(FUENTE, f"{BASE_URL}/{filename}", release)
        check_header(raw_dir / record.archivo, expected)
        records.append(record)

    # Si ChEBI publicó un release durante la descarga, los archivos podrían mezclar
    # versiones bajo la misma carpeta: se detiene en lugar de registrarlos.
    final = parse_release(downloader.fetch_text(FUENTE, README_URL))
    if final != release:
        raise SourceFormatError(
            f"ChEBI cambió de release durante la descarga ({release} -> {final}); "
            "vuelve a ejecutar la extracción."
        )
    return release, records
