"""Extractor de ChEBI (sección 3 de docs/MANUAL.md): compuestos, nombres y ontología.

Descarga los archivos TSV de `flat_files/` del FTP oficial de EMBL-EBI, que solo
contienen IDs primarios, junto con su README, que declara el número de release.

TODO: `structures.tsv.gz` (SMILES e InChI, ~89 MB) y `reference.tsv.gz` (~131 MB)
todavía no se descargan; se agregan cuando una etapa los use.
"""

from __future__ import annotations

import csv
import gzip
import html
import re
from collections.abc import Iterable, Iterator
from dataclasses import dataclass
from pathlib import Path

from metabo.download import Downloader
from metabo.errors import SourceFormatError
from metabo.manifest import DownloadRecord
from metabo.sources.formats import check_header, find_release

FUENTE = "chebi"
BASE_URL = "https://ftp.ebi.ac.uk/pub/databases/chebi/flat_files"
README_URL = f"{BASE_URL}/README"

_RELEASE = r"^\*\s*ChEBI Release:\s*([0-9]+)\s*$"

# Archivo -> encabezado esperado (copiado de los archivos del release 256).
TSV_FILES: dict[str, tuple[str, ...]] = {
    "compounds.tsv.gz": (
        "id",
        "name",
        "status_id",
        "source",
        "parent_id",
        "merge_type",
        "chebi_accession",
        "definition",
        "ascii_name",
        "stars",
        "modified_on",
        "release_date",
    ),
    "chemical_data.tsv.gz": (
        "id",
        "compound_id",
        "formula",
        "charge",
        "mass",
        "monoisotopic_mass",
        "status_id",
        "structure_id",
        "is_autogenerated",
    ),
    "names.tsv.gz": (
        "id",
        "compound_id",
        "name",
        "type",
        "status_id",
        "adapted",
        "language_code",
        "ascii_name",
    ),
    "relation.tsv.gz": (
        "id",
        "relation_type_id",
        "init_id",
        "final_id",
        "status_id",
        "evidence_accession",
        "evidence_source_id",
    ),
    "relation_type.tsv.gz": ("id", "code", "allow_cycles", "description"),
    "secondary_ids.tsv.gz": ("compound_id", "secondary_id"),
}


def parse_release(text: str) -> str:
    """Número de release declarado en el README de flat_files/."""
    return find_release(text, _RELEASE, "el README de ChEBI flat_files")


def extract(downloader: Downloader, raw_dir: Path) -> tuple[str, list[DownloadRecord]]:
    """Descarga la versión vigente de ChEBI a raw/chebi/<release>/."""
    release = parse_release(downloader.fetch_text(FUENTE, README_URL))

    records = [downloader.download(FUENTE, README_URL, release)]
    for filename, expected in TSV_FILES.items():
        record = downloader.download(FUENTE, f"{BASE_URL}/{filename}", release)
        check_header(raw_dir / record.archivo, expected)
        records.append(record)

    # Si ChEBI publicó un release durante la descarga, los archivos podrían mezclar
    # versiones bajo la misma carpeta: se detiene en lugar de registrarlos.
    final = parse_release(downloader.fetch_text(FUENTE, README_URL))
    if final != release:
        raise SourceFormatError(
            f"ChEBI cambió de release durante la descarga ({release} -> {final}); "
            "vuelve a ejecutar la extracción."
        )
    return release, records


def read_compound_names(path: Path) -> dict[str, str]:
    """compounds.tsv.gz: ID primario (CURIE, p. ej. CHEBI:15361) -> nombre en inglés."""
    csv.field_size_limit(1 << 24)
    with gzip.open(path, "rt", encoding="utf-8", newline="") as handle:
        return {
            row["chebi_accession"]: row["name"] for row in csv.DictReader(handle, delimiter="\t")
        }


# ---------------------------------------------------------------------------
# Lectura de compuestos y ontología para el paquete de datos
# ---------------------------------------------------------------------------

# Relaciones de la ontología que se siguen para clasificar un compuesto: "es un" y
# ácido/base conjugados (Rhea usa la forma iónica a pH 7,3, y ChEBI clasifica muchas
# veces la forma neutra).
ONTOLOGY_RELATIONS = ("is_a", "is_conjugate_acid_of", "is_conjugate_base_of")
# Tipos de nombre de names.tsv que se exportan como sinónimos.
SYNONYM_TYPES = ("SYNONYM", "IUPAC NAME", "UNIPROT NAME")

_TAG = re.compile(r"<[^>]+>")


def plain_text(value: str) -> str:
    """Quita las etiquetas HTML que ChEBI usa en los nombres (<small>D</small>, <em>…</em>)."""
    return html.unescape(_TAG.sub("", value)).strip()


@dataclass(frozen=True)
class Compound:
    id: str  # CURIE
    nombre: str
    definicion: str | None
    sinonimos: tuple[str, ...]
    formula: str | None
    carga: int | None
    masa_monoisotopica: float | None


def _rows(path: Path) -> Iterator[dict[str, str]]:
    csv.field_size_limit(1 << 24)
    with gzip.open(path, "rt", encoding="utf-8", newline="") as handle:
        yield from csv.DictReader(handle, delimiter="\t")


def _number(value: str) -> float | None:
    return float(value) if value.strip() else None


def read_compounds(raw_files: dict[str, Path], wanted: Iterable[str]) -> dict[str, Compound]:
    """Datos de los compuestos pedidos (CURIE) desde compounds, chemical_data y names.

    `raw_files` asocia cada nombre de archivo de TSV_FILES con su ruta. Si un compuesto
    tiene varias filas en chemical_data, se usa la de menor `id`.
    """
    wanted = set(wanted)
    base: dict[str, dict[str, str]] = {}
    for row in _rows(raw_files["compounds.tsv.gz"]):
        if row["chebi_accession"] in wanted:
            base[row["id"]] = row
    missing = wanted - {row["chebi_accession"] for row in base.values()}
    if missing:
        raise SourceFormatError(
            f"compounds.tsv.gz no tiene {', '.join(sorted(missing))} como ID primario."
        )

    chemical: dict[str, dict[str, str]] = {}
    for row in _rows(raw_files["chemical_data.tsv.gz"]):
        cid = row["compound_id"]
        if cid in base and (cid not in chemical or int(row["id"]) < int(chemical[cid]["id"])):
            chemical[cid] = row

    synonyms: dict[str, list[str]] = {}
    for row in _rows(raw_files["names.tsv.gz"]):
        if row["compound_id"] in base and row["type"] in SYNONYM_TYPES:
            synonyms.setdefault(row["compound_id"], []).append(plain_text(row["name"]))

    compounds = {}
    for cid, row in base.items():
        name = plain_text(row["name"])
        data = chemical.get(cid, {})
        charge = data.get("charge", "").strip()
        compounds[row["chebi_accession"]] = Compound(
            id=row["chebi_accession"],
            nombre=name,
            definicion=plain_text(row["definition"]) or None,
            sinonimos=tuple(dict.fromkeys(s for s in synonyms.get(cid, []) if s and s != name)),
            formula=data.get("formula") or None,
            carga=int(charge) if charge else None,
            masa_monoisotopica=_number(data.get("monoisotopic_mass", "")),
        )
    return compounds


def read_ontology(relation: Path, relation_type: Path) -> dict[str, frozenset[str]]:
    """Grafo de ONTOLOGY_RELATIONS: compuesto (CURIE) -> compuestos a los que apunta."""
    codes = {row["id"]: row["code"] for row in _rows(relation_type)}
    unknown = set(ONTOLOGY_RELATIONS) - set(codes.values())
    if unknown:
        raise SourceFormatError(f"relation_type.tsv.gz no tiene {', '.join(sorted(unknown))}.")
    edges: dict[str, set[str]] = {}
    for row in _rows(relation):
        if codes.get(row["relation_type_id"]) in ONTOLOGY_RELATIONS:
            edges.setdefault(f"CHEBI:{row['init_id']}", set()).add(f"CHEBI:{row['final_id']}")
    return {k: frozenset(v) for k, v in edges.items()}


def ancestors(compound: str, ontology: dict[str, frozenset[str]]) -> frozenset[str]:
    """Todos los nodos alcanzables desde `compound` en el grafo (sin incluirlo)."""
    seen: set[str] = set()
    pending = [compound]
    while pending:
        for parent in ontology.get(pending.pop(), ()):
            if parent not in seen:
                seen.add(parent)
                pending.append(parent)
    seen.discard(compound)
    return frozenset(seen)
